from django.urls import path
from .views import (
    ProfileListView,
    ProfileCreateView,
    ProfileDetailView,
    ProfileUpdateView,
    ProfileDeleteView,
    EducationListView,
    EducationCreateView,
    EducationDetailView,
    EducationUpdateView,
    EducationDeleteView,
    ExperienceListView,
    ExperienceCreateView,
    ExperienceDetailView,
    ExperienceUpdateView,
    ExperienceDeleteView,
    SocialCreateView,
    SocialDetailView,
    SocialUpdateView,
    SocialDeleteView
)

app_name = 'profiles'
urlpatterns = [
    path(
        '',
        ProfileListView.as_view(),
        name='profiles-list'
    ),
    path(
        'create/',
        ProfileCreateView.as_view(),
        name='profiles-create'
    ),
    path(
        '<int:id>/detail/',
        ProfileDetailView.as_view(),
        name='profiles-detail'
    ),
    path(
        '<int:id>/delete/',
        ProfileDeleteView.as_view(),
        name='profiles-delete'
    ),
    path(
        '<int:id>/update/',
        ProfileUpdateView.as_view(),
        name='profiles-update'
    ),
    path(
        '<int:id>/educations/',
        EducationListView.as_view(),
        name='educations-list'
    ),
    path(
        '<int:id>/experiences/',
        ExperienceListView.as_view(),
        name='experiences-list'
    ),
    path(
        '<int:id>/educations/create',
        EducationCreateView.as_view(),
        name='educations-create'
    ),
    path(
        '<int:id>/experiences/create',
        ExperienceCreateView.as_view(),
        name='experiences-create'
    ),
    path(
        '<int:id>/socials',
        SocialDetailView.as_view(),
        name='socials-detail'
    ),
    path(
        '<int:id>/socials/create',
        SocialCreateView.as_view(),
        name='socials-create'
    ),
    path(
        '<int:id>/socials/update',
        SocialUpdateView.as_view(),
        name='socials-update'
    ),
    path(
        '<int:id>/socials/delete',
        SocialDeleteView.as_view(),
        name='socials-delete'
    ),
    path(
        '<int:profile_id>/educations/<int:education_id>/detail',
        EducationDetailView.as_view(),
        name='educations-detail'
    ),
    path(
        '<int:profile_id>/experiences/<int:experience_id>/detail',
        ExperienceDetailView.as_view(),
        name='experiences-detail'
    ),
    path(
        '<int:profile_id>/educations/<int:education_id>/update',
        EducationUpdateView.as_view(),
        name='educations-update'
    ),
    path(
        '<int:profile_id>/experiences/<int:experience_id>/update',
        ExperienceUpdateView.as_view(),
        name='experiences-update'
    ),
    path(
        '<int:profile_id>/educations/<int:education_id>/delete',
        EducationDeleteView.as_view(),
        name='educations-delete'
    ),
    path(
        '<int:profile_id>/experiences/<int:experience_id>/delete',
        ExperienceDeleteView.as_view(),
        name='experiences-delete'
    ),
]
